spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/corretagem
    username: postgres
    password: 1234@Mudar
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: M687BVD7FPUK567

